### ISSUE TITLE
AuthKey design

### ISSUE THREAD

**Issue by KevinZonda** [CraftStarStudio/MCDReforged-Remote#4]
Hello. I found that might our authKey design is sth wrong.

Usually, we use authKey like:

```
Client --(authKey)--> Server
```
Then, server compares:

```
sha512(authKey) == hash
```

But now, we have done is

```
Client --(sha512(authKey))--> Server
```

Then, server compares:

```
hash1 == hash2
```

I cannot say it is a wrong design, but it will not be a cool design.

I do NOT think we need:

https://github.com/CraftStarStudio/MCDReforged-Remote/blob/ba39111091e0a6937d7b24d0d05f0ac691afae00/MCDReforgedRemote.py#L185-L187

**Comment by Cubik65536** [comment]
The design of MCDReforged itself doesn't allow me to ask the user to set their password in a way other than writing down their key directly in the conf file. So we need this one:

https://github.com/CraftStarStudio/MCDReforged-Remote/blob/ba39111091e0a6937d7b24d0d05f0ac691afae00/MCDReforgedRemote.py#L185-L187

And because of that, I don't think that send the `auth_key` on plaintext will be a good idea.

**Comment by KevinZonda** [comment]
We can read passwd from conf right?

Why we need SHA512?

If you think use SHA512 can be safer, why allows user store unhashed passwd into file?

During transferring data between client and server, they must have at least one TLS layer.

**Comment by Cubik65536** [comment]
> We can read passwd from conf right?
> 
> Why we need SHA512?
> 
> If you think use SHA512 can be safer, why allows user store unhashed passwd into file?
> 
> During transferring data between client and server, they must have at least one TLS layer.

Then just remove the SHA512, I'm not sure if the user will enable TLS, so that's why I'm using it. Anyway, what you've said make sense and we are going to do this.

**Comment by KevinZonda** [comment]
It's nonsense that transfer data plainly. If user do so, that will be not our responsibility, cuz they r shit, we are not obliged to save waste.

**Comment by Cubik65536** [comment]
> It's nonsense that transfer data plainly. If user do so, that will be not our responsibility, cuz they r shit, we are not obliged to save waste.

I agree with you. Just remove it
